# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BV41filterCpp <- function(xt, wst, wss, nrowst, nrowss, maxt, maxs) {
    .Call('_deseats_BV41filterCpp', PACKAGE = 'deseats', xt, wst, wss, nrowst, nrowss, maxt, maxs)
}

ARinftySHORT <- function(ar, ma, max_i) {
    .Call('_deseats_ARinftySHORT', PACKAGE = 'deseats', ar, ma, max_i)
}

MAinftySHORT <- function(ar, ma, max_i) {
    .Call('_deseats_MAinftySHORT', PACKAGE = 'deseats', ar, ma, max_i)
}

ARinftyLONG <- function(ar, d_coef) {
    .Call('_deseats_ARinftyLONG', PACKAGE = 'deseats', ar, d_coef)
}

MAinftyLONG <- function(ma, d_coef) {
    .Call('_deseats_MAinftyLONG', PACKAGE = 'deseats', ma, d_coef)
}

fcastCpp <- function(X, innov, ar, ma, mu, h) {
    .Call('_deseats_fcastCpp', PACKAGE = 'deseats', X, innov, ar, ma, mu, h)
}

tfcastCpp <- function(X, innov, epsBoot, ar, ma, mu, h) {
    .Call('_deseats_tfcastCpp', PACKAGE = 'deseats', X, innov, epsBoot, ar, ma, mu, h)
}

seqCpp <- function(from, to) {
    .Call('_deseats_seqCpp', PACKAGE = 'deseats', from, to)
}

rseqCpp <- function(from, to) {
    .Call('_deseats_rseqCpp', PACKAGE = 'deseats', from, to)
}

factorialCpp <- function(k) {
    .Call('_deseats_factorialCpp', PACKAGE = 'deseats', k)
}

armaCpp <- function(Xt, p, q, armamean) {
    .Call('_deseats_armaCpp', PACKAGE = 'deseats', Xt, p, q, armamean)
}

BICarmaCpp <- function(Xt, p, q, armamean) {
    .Call('_deseats_BICarmaCpp', PACKAGE = 'deseats', Xt, p, q, armamean)
}

selectOrderBIC <- function(Xt, pmin, pmax, qmin, qmax, armamean) {
    .Call('_deseats_selectOrderBIC', PACKAGE = 'deseats', Xt, pmin, pmax, qmin, qmax, armamean)
}

armaoptCpp <- function(Xt, narmin, narmax, nmamin, nmamax, armamean) {
    .Call('_deseats_armaoptCpp', PACKAGE = 'deseats', Xt, narmin, narmax, nmamin, nmamax, armamean)
}

arma_sumacovCpp <- function(arma) {
    .Call('_deseats_arma_sumacovCpp', PACKAGE = 'deseats', arma)
}

acovCpp <- function(Xt, lagMax) {
    .Call('_deseats_acovCpp', PACKAGE = 'deseats', Xt, lagMax)
}

cf0Cpp <- function(Xt) {
    .Call('_deseats_cf0Cpp', PACKAGE = 'deseats', Xt)
}

fitteddeseatsCpp <- function(y, p, s, mu, b, bb) {
    .Call('_deseats_fitteddeseatsCpp', PACKAGE = 'deseats', y, p, s, mu, b, bb)
}

residdeseatsCpp <- function(y, p, s, mu, b, bb) {
    .Call('_deseats_residdeseatsCpp', PACKAGE = 'deseats', y, p, s, mu, b, bb)
}

derivdeseatsCpp <- function(y, p, s, mu, b, bb, v) {
    .Call('_deseats_derivdeseatsCpp', PACKAGE = 'deseats', y, p, s, mu, b, bb, v)
}

algorithmCpp <- function(yt, p, s, mu, bStart, CF, errors, cb, bb, errm, expo, narmin, narmax, nmamin, nmamax, armamean) {
    .Call('_deseats_algorithmCpp', PACKAGE = 'deseats', yt, p, s, mu, bStart, CF, errors, cb, bb, errm, expo, narmin, narmax, nmamin, nmamax, armamean)
}

wls_Cpp <- function(x, y, wk) {
    .Call('_deseats_wls_Cpp', PACKAGE = 'deseats', x, y, wk)
}

find_sub_Cpp <- function(t, t0, interior_bwidth, seasonality) {
    .Call('_deseats_find_sub_Cpp', PACKAGE = 'deseats', t, t0, interior_bwidth, seasonality)
}

llin_calc_Cpp <- function(yt, t, bwidth, P, mu, bb, seasonality) {
    .Call('_deseats_llin_calc_Cpp', PACKAGE = 'deseats', yt, t, bwidth, P, mu, bb, seasonality)
}

